# Production Docker Compose dengan nginx reverse proxy
services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./uploads:/uploads:ro
    depends_on:
      - object-storage
    networks:
      - storage-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Object Storage Server
  object-storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: object-storage-server
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - PORT=8080
      - BASE_URL=${BASE_URL:-http://localhost}
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-4294967296}  # 4GB default
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-*}
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env:ro
    networks:
      - storage-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G

networks:
  storage-network:
    driver: bridge
