services:
  object-storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: object-storage-server
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=${PORT:-8080}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - UPLOAD_DIR=/app/uploads
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-4294967296}  # 4GB default
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS:-*}
    volumes:
      # Persistent storage untuk uploaded files
      - ./uploads:/app/uploads
      # Optional: Mount .env file
      - ./.env:/app/.env:ro
    networks:
      - storage-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits (optional, adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  storage-network:
    driver: bridge
